services:
  app:
    image: cosmtrek/air
    working_dir: /app
    ports:
      - 8080:8080
    environment:
      LIVE_RELOAD: true
      SQLITE_URI: "./dev.db"
    volumes:
      - .:/app
  
  livereload:
    build:
      dockerfile: docker/Dockerfile.livereload
      context: .
    ports:
      - 5555:5555
  
  tailwind:
    build:
      dockerfile: docker/Dockerfile.tailwind
      context: .
    command:  ["./tailwindcss", "-c", "project/tailwind.config.js", "-i", "project/assets/dev.css", "-o", "project/assets/style.css", "--watch"]
    volumes:
      - .:/tailwind/project/