FROM debian:stable-slim

WORKDIR /tailwind

RUN apt-get update \
  && apt-get install -y wget \
  && apt-get clean

RUN wget https://github.com/tailwindlabs/tailwindcss/releases/latest/download/tailwindcss-linux-x64 \
  && mv tailwindcss-linux-x64 tailwindcss \
  && chmod +x tailwindcss
